version: '2'
services:
  jeecg-boot-system:
    build:
      context: ./jeecg-boot/jeecg-server-cloud/jeecg-system-cloud-start
    container_name: jeecg-system-start
    ports:
      - 7001:7001
    hostname: jeecg-boot-system
    environment:
      - TZ=Asia/Shanghai
    networks:
      - software_default

  jeecg-boot-gateway:
    build:
      context: ./jeecg-boot/jeecg-server-cloud/jeecg-cloud-gateway
    ports:
      - 9999:9999
    depends_on:
      - jeecg-boot-system
    container_name: jeecg-boot-gateway
    hostname: jeecg-boot-gateway
    networks:
      - software_default

  jeecg-vue:
    build:
      context: ./jeecgboot-vue3
    container_name: jeecgboot-vue3-nginx
    image: jeecgboot-vue3
    depends_on:
      - jeecg-boot-system
    ports:
      - 8888:80
    networks:
      - software_default

networks:
  software_default:
    external: true
