server:
  port: 7001

spring:
  application:
    name: jeecg-system
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    nacos:
      server-addr: @config.server-addr@
      username: @config.username@
      password: @config.password@
      config:
        enabled: true
        group: @config.group@
        namespace: @config.namespace@
        file-extension: yaml
      discovery:
        enabled: true
        group: @config.group@
        namespace: @config.namespace@
  config:
    import:
      - optional:nacos:jeecg.yaml
      - optional:nacos:jeecg-@profile.name@.yaml